[build]
  publish = "/"
  command = "echo 'nothing to build'"

[[redirects]]
  from = "/.well-known/*"
  to = "/.well-known/:splat"
  status = 200
  force = true

[[headers]]
  for = "/.well-known/*"
  [headers.values]
    Content-Type = "text/plain"
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type"
