[[ISSUERS]]
address = "rUQDycPkQ1XLehCUhY7R44cGBqpfx4JyBF"
name = "JEET"

[[ACCOUNTS]]
address = "rUQDycPkQ1XLehCUhY7R44cGBqpfx4JyBF"
desc = "desc"
domain = "https://dfasfasfasfasfs.netlify.app/"

[[TOKENS]]
issuer = "rUQDycPkQ1XLehCUhY7R44cGBqpfx4JyBF"
currency = "JEET"
name = "Jeeter Pan"
desc = "adventuring never land, jeeting every 1 XRP we make for pixie dust."
icon = "https://pbs.twimg.com/profile_images/1864177329225773056/DG2zG3pw_400x400.jpg"

[[TOKENS.WEBLINKS]]
url = "https://x.com"
type = "website"
title = "Official Website"

[[TOKENS.WEBLINKS]]
url = "https://x.com/jeetcoinxrp"
type = "socialmedia"
